# Generated by Django 3.0.7 on 2020-06-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200628_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
