# Generated by Django 3.0.7 on 2020-06-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuimg',
            field=models.FileField(upload_to=''),
        ),
    ]
