# Generated by Django 3.0.7 on 2020-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200628_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuimg',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
